using System;
namespace ResearchWebApi.Models
{
    public class MaModel
    {
        public double? Ma1 { get; set; }
        public double? Ma2 { get; set; }
        public double? Ma3 { get; set; }
        public double? Ma4 { get; set; }
        public double? Ma5 { get; set; }
        public double? Ma6 { get; set; }
        public double? Ma7 { get; set; }
        public double? Ma8 { get; set; }
        public double? Ma9 { get; set; }
        public double? Ma10 { get; set; }
        public double? Ma11 { get; set; }
        public double? Ma12 { get; set; }
        public double? Ma13 { get; set; }
        public double? Ma14 { get; set; }
        public double? Ma15 { get; set; }
        public double? Ma16 { get; set; }
        public double? Ma17 { get; set; }
        public double? Ma18 { get; set; }
        public double? Ma19 { get; set; }
        public double? Ma20 { get; set; }
        public double? Ma21 { get; set; }
        public double? Ma22 { get; set; }
        public double? Ma23 { get; set; }
        public double? Ma24 { get; set; }
        public double? Ma25 { get; set; }
        public double? Ma26 { get; set; }
        public double? Ma27 { get; set; }
        public double? Ma28 { get; set; }
        public double? Ma29 { get; set; }
        public double? Ma30 { get; set; }
        public double? Ma31 { get; set; }
        public double? Ma32 { get; set; }
        public double? Ma33 { get; set; }
        public double? Ma34 { get; set; }
        public double? Ma35 { get; set; }
        public double? Ma36 { get; set; }
        public double? Ma37 { get; set; }
        public double? Ma38 { get; set; }
        public double? Ma39 { get; set; }
        public double? Ma40 { get; set; }
        public double? Ma41 { get; set; }
        public double? Ma42 { get; set; }
        public double? Ma43 { get; set; }
        public double? Ma44 { get; set; }
        public double? Ma45 { get; set; }
        public double? Ma46 { get; set; }
        public double? Ma47 { get; set; }
        public double? Ma48 { get; set; }
        public double? Ma49 { get; set; }
        public double? Ma50 { get; set; }
        public double? Ma51 { get; set; }
        public double? Ma52 { get; set; }
        public double? Ma53 { get; set; }
        public double? Ma54 { get; set; }
        public double? Ma55 { get; set; }
        public double? Ma56 { get; set; }
        public double? Ma57 { get; set; }
        public double? Ma58 { get; set; }
        public double? Ma59 { get; set; }
        public double? Ma60 { get; set; }
        public double? Ma61 { get; set; }
        public double? Ma62 { get; set; }
        public double? Ma63 { get; set; }
        public double? Ma64 { get; set; }
        public double? Ma65 { get; set; }
        public double? Ma66 { get; set; }
        public double? Ma67 { get; set; }
        public double? Ma68 { get; set; }
        public double? Ma69 { get; set; }
        public double? Ma70 { get; set; }
        public double? Ma71 { get; set; }
        public double? Ma72 { get; set; }
        public double? Ma73 { get; set; }
        public double? Ma74 { get; set; }
        public double? Ma75 { get; set; }
        public double? Ma76 { get; set; }
        public double? Ma77 { get; set; }
        public double? Ma78 { get; set; }
        public double? Ma79 { get; set; }
        public double? Ma80 { get; set; }
        public double? Ma81 { get; set; }
        public double? Ma82 { get; set; }
        public double? Ma83 { get; set; }
        public double? Ma84 { get; set; }
        public double? Ma85 { get; set; }
        public double? Ma86 { get; set; }
        public double? Ma87 { get; set; }
        public double? Ma88 { get; set; }
        public double? Ma89 { get; set; }
        public double? Ma90 { get; set; }
        public double? Ma91 { get; set; }
        public double? Ma92 { get; set; }
        public double? Ma93 { get; set; }
        public double? Ma94 { get; set; }
        public double? Ma95 { get; set; }
        public double? Ma96 { get; set; }
        public double? Ma97 { get; set; }
        public double? Ma98 { get; set; }
        public double? Ma99 { get; set; }
        public double? Ma100 { get; set; }
        public double? Ma101 { get; set; }
        public double? Ma102 { get; set; }
        public double? Ma103 { get; set; }
        public double? Ma104 { get; set; }
        public double? Ma105 { get; set; }
        public double? Ma106 { get; set; }
        public double? Ma107 { get; set; }
        public double? Ma108 { get; set; }
        public double? Ma109 { get; set; }
        public double? Ma110 { get; set; }
        public double? Ma111 { get; set; }
        public double? Ma112 { get; set; }
        public double? Ma113 { get; set; }
        public double? Ma114 { get; set; }
        public double? Ma115 { get; set; }
        public double? Ma116 { get; set; }
        public double? Ma117 { get; set; }
        public double? Ma118 { get; set; }
        public double? Ma119 { get; set; }
        public double? Ma120 { get; set; }
        public double? Ma121 { get; set; }
        public double? Ma122 { get; set; }
        public double? Ma123 { get; set; }
        public double? Ma124 { get; set; }
        public double? Ma125 { get; set; }
        public double? Ma126 { get; set; }
        public double? Ma127 { get; set; }
        public double? Ma128 { get; set; }
        public double? Ma129 { get; set; }
        public double? Ma130 { get; set; }
        public double? Ma131 { get; set; }
        public double? Ma132 { get; set; }
        public double? Ma133 { get; set; }
        public double? Ma134 { get; set; }
        public double? Ma135 { get; set; }
        public double? Ma136 { get; set; }
        public double? Ma137 { get; set; }
        public double? Ma138 { get; set; }
        public double? Ma139 { get; set; }
        public double? Ma140 { get; set; }
        public double? Ma141 { get; set; }
        public double? Ma142 { get; set; }
        public double? Ma143 { get; set; }
        public double? Ma144 { get; set; }
        public double? Ma145 { get; set; }
        public double? Ma146 { get; set; }
        public double? Ma147 { get; set; }
        public double? Ma148 { get; set; }
        public double? Ma149 { get; set; }
        public double? Ma150 { get; set; }
        public double? Ma151 { get; set; }
        public double? Ma152 { get; set; }
        public double? Ma153 { get; set; }
        public double? Ma154 { get; set; }
        public double? Ma155 { get; set; }
        public double? Ma156 { get; set; }
        public double? Ma157 { get; set; }
        public double? Ma158 { get; set; }
        public double? Ma159 { get; set; }
        public double? Ma160 { get; set; }
        public double? Ma161 { get; set; }
        public double? Ma162 { get; set; }
        public double? Ma163 { get; set; }
        public double? Ma164 { get; set; }
        public double? Ma165 { get; set; }
        public double? Ma166 { get; set; }
        public double? Ma167 { get; set; }
        public double? Ma168 { get; set; }
        public double? Ma169 { get; set; }
        public double? Ma170 { get; set; }
        public double? Ma171 { get; set; }
        public double? Ma172 { get; set; }
        public double? Ma173 { get; set; }
        public double? Ma174 { get; set; }
        public double? Ma175 { get; set; }
        public double? Ma176 { get; set; }
        public double? Ma177 { get; set; }
        public double? Ma178 { get; set; }
        public double? Ma179 { get; set; }
        public double? Ma180 { get; set; }
        public double? Ma181 { get; set; }
        public double? Ma182 { get; set; }
        public double? Ma183 { get; set; }
        public double? Ma184 { get; set; }
        public double? Ma185 { get; set; }
        public double? Ma186 { get; set; }
        public double? Ma187 { get; set; }
        public double? Ma188 { get; set; }
        public double? Ma189 { get; set; }
        public double? Ma190 { get; set; }
        public double? Ma191 { get; set; }
        public double? Ma192 { get; set; }
        public double? Ma193 { get; set; }
        public double? Ma194 { get; set; }
        public double? Ma195 { get; set; }
        public double? Ma196 { get; set; }
        public double? Ma197 { get; set; }
        public double? Ma198 { get; set; }
        public double? Ma199 { get; set; }
        public double? Ma200 { get; set; }
        public double? Ma201 { get; set; }
        public double? Ma202 { get; set; }
        public double? Ma203 { get; set; }
        public double? Ma204 { get; set; }
        public double? Ma205 { get; set; }
        public double? Ma206 { get; set; }
        public double? Ma207 { get; set; }
        public double? Ma208 { get; set; }
        public double? Ma209 { get; set; }
        public double? Ma210 { get; set; }
        public double? Ma211 { get; set; }
        public double? Ma212 { get; set; }
        public double? Ma213 { get; set; }
        public double? Ma214 { get; set; }
        public double? Ma215 { get; set; }
        public double? Ma216 { get; set; }
        public double? Ma217 { get; set; }
        public double? Ma218 { get; set; }
        public double? Ma219 { get; set; }
        public double? Ma220 { get; set; }
        public double? Ma221 { get; set; }
        public double? Ma222 { get; set; }
        public double? Ma223 { get; set; }
        public double? Ma224 { get; set; }
        public double? Ma225 { get; set; }
        public double? Ma226 { get; set; }
        public double? Ma227 { get; set; }
        public double? Ma228 { get; set; }
        public double? Ma229 { get; set; }
        public double? Ma230 { get; set; }
        public double? Ma231 { get; set; }
        public double? Ma232 { get; set; }
        public double? Ma233 { get; set; }
        public double? Ma234 { get; set; }
        public double? Ma235 { get; set; }
        public double? Ma236 { get; set; }
        public double? Ma237 { get; set; }
        public double? Ma238 { get; set; }
        public double? Ma239 { get; set; }
        public double? Ma240 { get; set; }
        public double? Ma241 { get; set; }
        public double? Ma242 { get; set; }
        public double? Ma243 { get; set; }
        public double? Ma244 { get; set; }
        public double? Ma245 { get; set; }
        public double? Ma246 { get; set; }
        public double? Ma247 { get; set; }
        public double? Ma248 { get; set; }
        public double? Ma249 { get; set; }
        public double? Ma250 { get; set; }
        public double? Ma251 { get; set; }
        public double? Ma252 { get; set; }
        public double? Ma253 { get; set; }
        public double? Ma254 { get; set; }
        public double? Ma255 { get; set; }
        public double? Ma256 { get; set; }

        public MaModel()
        {
        }
    }
}
