using System;
namespace ResearchWebApi.Models
{
    public class RsiModel
    {
        public decimal Rsi1 { get; set; }
        public decimal Rsi2 { get; set; }
        public decimal Rsi3 { get; set; }
        public decimal Rsi4 { get; set; }
        public decimal Rsi5 { get; set; }
        public decimal Rsi6 { get; set; }
        public decimal Rsi7 { get; set; }
        public decimal Rsi8 { get; set; }
        public decimal Rsi9 { get; set; }
        public decimal Rsi10 { get; set; }
        public decimal Rsi11 { get; set; }
        public decimal Rsi12 { get; set; }
        public decimal Rsi13 { get; set; }
        public decimal Rsi14 { get; set; }
        public decimal Rsi15 { get; set; }
        public decimal Rsi16 { get; set; }
        public decimal Rsi17 { get; set; }
        public decimal Rsi18 { get; set; }
        public decimal Rsi19 { get; set; }
        public decimal Rsi20 { get; set; }
        public decimal Rsi21 { get; set; }
        public decimal Rsi22 { get; set; }
        public decimal Rsi23 { get; set; }
        public decimal Rsi24 { get; set; }
        public decimal Rsi25 { get; set; }
        public decimal Rsi26 { get; set; }
        public decimal Rsi27 { get; set; }
        public decimal Rsi28 { get; set; }
        public decimal Rsi29 { get; set; }
        public decimal Rsi30 { get; set; }
        public decimal Rsi31 { get; set; }
        public decimal Rsi32 { get; set; }
        public decimal Rsi33 { get; set; }
        public decimal Rsi34 { get; set; }
        public decimal Rsi35 { get; set; }
        public decimal Rsi36 { get; set; }
        public decimal Rsi37 { get; set; }
        public decimal Rsi38 { get; set; }
        public decimal Rsi39 { get; set; }
        public decimal Rsi40 { get; set; }
        public decimal Rsi41 { get; set; }
        public decimal Rsi42 { get; set; }
        public decimal Rsi43 { get; set; }
        public decimal Rsi44 { get; set; }
        public decimal Rsi45 { get; set; }
        public decimal Rsi46 { get; set; }
        public decimal Rsi47 { get; set; }
        public decimal Rsi48 { get; set; }
        public decimal Rsi49 { get; set; }
        public decimal Rsi50 { get; set; }
        public decimal Rsi51 { get; set; }
        public decimal Rsi52 { get; set; }
        public decimal Rsi53 { get; set; }
        public decimal Rsi54 { get; set; }
        public decimal Rsi55 { get; set; }
        public decimal Rsi56 { get; set; }
        public decimal Rsi57 { get; set; }
        public decimal Rsi58 { get; set; }
        public decimal Rsi59 { get; set; }
        public decimal Rsi60 { get; set; }
        public decimal Rsi61 { get; set; }
        public decimal Rsi62 { get; set; }
        public decimal Rsi63 { get; set; }
        public decimal Rsi64 { get; set; }
        public decimal Rsi65 { get; set; }
        public decimal Rsi66 { get; set; }
        public decimal Rsi67 { get; set; }
        public decimal Rsi68 { get; set; }
        public decimal Rsi69 { get; set; }
        public decimal Rsi70 { get; set; }
        public decimal Rsi71 { get; set; }
        public decimal Rsi72 { get; set; }
        public decimal Rsi73 { get; set; }
        public decimal Rsi74 { get; set; }
        public decimal Rsi75 { get; set; }
        public decimal Rsi76 { get; set; }
        public decimal Rsi77 { get; set; }
        public decimal Rsi78 { get; set; }
        public decimal Rsi79 { get; set; }
        public decimal Rsi80 { get; set; }
        public decimal Rsi81 { get; set; }
        public decimal Rsi82 { get; set; }
        public decimal Rsi83 { get; set; }
        public decimal Rsi84 { get; set; }
        public decimal Rsi85 { get; set; }
        public decimal Rsi86 { get; set; }
        public decimal Rsi87 { get; set; }
        public decimal Rsi88 { get; set; }
        public decimal Rsi89 { get; set; }
        public decimal Rsi90 { get; set; }
        public decimal Rsi91 { get; set; }
        public decimal Rsi92 { get; set; }
        public decimal Rsi93 { get; set; }
        public decimal Rsi94 { get; set; }
        public decimal Rsi95 { get; set; }
        public decimal Rsi96 { get; set; }
        public decimal Rsi97 { get; set; }
        public decimal Rsi98 { get; set; }
        public decimal Rsi99 { get; set; }
        public decimal Rsi100 { get; set; }
        public decimal Rsi101 { get; set; }
        public decimal Rsi102 { get; set; }
        public decimal Rsi103 { get; set; }
        public decimal Rsi104 { get; set; }
        public decimal Rsi105 { get; set; }
        public decimal Rsi106 { get; set; }
        public decimal Rsi107 { get; set; }
        public decimal Rsi108 { get; set; }
        public decimal Rsi109 { get; set; }
        public decimal Rsi110 { get; set; }
        public decimal Rsi111 { get; set; }
        public decimal Rsi112 { get; set; }
        public decimal Rsi113 { get; set; }
        public decimal Rsi114 { get; set; }
        public decimal Rsi115 { get; set; }
        public decimal Rsi116 { get; set; }
        public decimal Rsi117 { get; set; }
        public decimal Rsi118 { get; set; }
        public decimal Rsi119 { get; set; }
        public decimal Rsi120 { get; set; }
        public decimal Rsi121 { get; set; }
        public decimal Rsi122 { get; set; }
        public decimal Rsi123 { get; set; }
        public decimal Rsi124 { get; set; }
        public decimal Rsi125 { get; set; }
        public decimal Rsi126 { get; set; }
        public decimal Rsi127 { get; set; }
        public decimal Rsi128 { get; set; }
        public decimal Rsi129 { get; set; }
        public decimal Rsi130 { get; set; }
        public decimal Rsi131 { get; set; }
        public decimal Rsi132 { get; set; }
        public decimal Rsi133 { get; set; }
        public decimal Rsi134 { get; set; }
        public decimal Rsi135 { get; set; }
        public decimal Rsi136 { get; set; }
        public decimal Rsi137 { get; set; }
        public decimal Rsi138 { get; set; }
        public decimal Rsi139 { get; set; }
        public decimal Rsi140 { get; set; }
        public decimal Rsi141 { get; set; }
        public decimal Rsi142 { get; set; }
        public decimal Rsi143 { get; set; }
        public decimal Rsi144 { get; set; }
        public decimal Rsi145 { get; set; }
        public decimal Rsi146 { get; set; }
        public decimal Rsi147 { get; set; }
        public decimal Rsi148 { get; set; }
        public decimal Rsi149 { get; set; }
        public decimal Rsi150 { get; set; }
        public decimal Rsi151 { get; set; }
        public decimal Rsi152 { get; set; }
        public decimal Rsi153 { get; set; }
        public decimal Rsi154 { get; set; }
        public decimal Rsi155 { get; set; }
        public decimal Rsi156 { get; set; }
        public decimal Rsi157 { get; set; }
        public decimal Rsi158 { get; set; }
        public decimal Rsi159 { get; set; }
        public decimal Rsi160 { get; set; }
        public decimal Rsi161 { get; set; }
        public decimal Rsi162 { get; set; }
        public decimal Rsi163 { get; set; }
        public decimal Rsi164 { get; set; }
        public decimal Rsi165 { get; set; }
        public decimal Rsi166 { get; set; }
        public decimal Rsi167 { get; set; }
        public decimal Rsi168 { get; set; }
        public decimal Rsi169 { get; set; }
        public decimal Rsi170 { get; set; }
        public decimal Rsi171 { get; set; }
        public decimal Rsi172 { get; set; }
        public decimal Rsi173 { get; set; }
        public decimal Rsi174 { get; set; }
        public decimal Rsi175 { get; set; }
        public decimal Rsi176 { get; set; }
        public decimal Rsi177 { get; set; }
        public decimal Rsi178 { get; set; }
        public decimal Rsi179 { get; set; }
        public decimal Rsi180 { get; set; }
        public decimal Rsi181 { get; set; }
        public decimal Rsi182 { get; set; }
        public decimal Rsi183 { get; set; }
        public decimal Rsi184 { get; set; }
        public decimal Rsi185 { get; set; }
        public decimal Rsi186 { get; set; }
        public decimal Rsi187 { get; set; }
        public decimal Rsi188 { get; set; }
        public decimal Rsi189 { get; set; }
        public decimal Rsi190 { get; set; }
        public decimal Rsi191 { get; set; }
        public decimal Rsi192 { get; set; }
        public decimal Rsi193 { get; set; }
        public decimal Rsi194 { get; set; }
        public decimal Rsi195 { get; set; }
        public decimal Rsi196 { get; set; }
        public decimal Rsi197 { get; set; }
        public decimal Rsi198 { get; set; }
        public decimal Rsi199 { get; set; }
        public decimal Rsi200 { get; set; }
        public decimal Rsi201 { get; set; }
        public decimal Rsi202 { get; set; }
        public decimal Rsi203 { get; set; }
        public decimal Rsi204 { get; set; }
        public decimal Rsi205 { get; set; }
        public decimal Rsi206 { get; set; }
        public decimal Rsi207 { get; set; }
        public decimal Rsi208 { get; set; }
        public decimal Rsi209 { get; set; }
        public decimal Rsi210 { get; set; }
        public decimal Rsi211 { get; set; }
        public decimal Rsi212 { get; set; }
        public decimal Rsi213 { get; set; }
        public decimal Rsi214 { get; set; }
        public decimal Rsi215 { get; set; }
        public decimal Rsi216 { get; set; }
        public decimal Rsi217 { get; set; }
        public decimal Rsi218 { get; set; }
        public decimal Rsi219 { get; set; }
        public decimal Rsi220 { get; set; }
        public decimal Rsi221 { get; set; }
        public decimal Rsi222 { get; set; }
        public decimal Rsi223 { get; set; }
        public decimal Rsi224 { get; set; }
        public decimal Rsi225 { get; set; }
        public decimal Rsi226 { get; set; }
        public decimal Rsi227 { get; set; }
        public decimal Rsi228 { get; set; }
        public decimal Rsi229 { get; set; }
        public decimal Rsi230 { get; set; }
        public decimal Rsi231 { get; set; }
        public decimal Rsi232 { get; set; }
        public decimal Rsi233 { get; set; }
        public decimal Rsi234 { get; set; }
        public decimal Rsi235 { get; set; }
        public decimal Rsi236 { get; set; }
        public decimal Rsi237 { get; set; }
        public decimal Rsi238 { get; set; }
        public decimal Rsi239 { get; set; }
        public decimal Rsi240 { get; set; }
        public decimal Rsi241 { get; set; }
        public decimal Rsi242 { get; set; }
        public decimal Rsi243 { get; set; }
        public decimal Rsi244 { get; set; }
        public decimal Rsi245 { get; set; }
        public decimal Rsi246 { get; set; }
        public decimal Rsi247 { get; set; }
        public decimal Rsi248 { get; set; }
        public decimal Rsi249 { get; set; }
        public decimal Rsi250 { get; set; }
        public decimal Rsi251 { get; set; }
        public decimal Rsi252 { get; set; }
        public decimal Rsi253 { get; set; }
        public decimal Rsi254 { get; set; }
        public decimal Rsi255 { get; set; }
        public decimal Rsi256 { get; set; }

        public RsiModel()
        {
        }
    }
}
