using System;
namespace ResearchWebApi.Models
{
    public class RsiModel
    {
        public double? Rsi1 { get; set; }
        public double? Rsi2 { get; set; }
        public double? Rsi3 { get; set; }
        public double? Rsi4 { get; set; }
        public double? Rsi5 { get; set; }
        public double? Rsi6 { get; set; }
        public double? Rsi7 { get; set; }
        public double? Rsi8 { get; set; }
        public double? Rsi9 { get; set; }
        public double? Rsi10 { get; set; }
        public double? Rsi11 { get; set; }
        public double? Rsi12 { get; set; }
        public double? Rsi13 { get; set; }
        public double? Rsi14 { get; set; }
        public double? Rsi15 { get; set; }
        public double? Rsi16 { get; set; }
        public double? Rsi17 { get; set; }
        public double? Rsi18 { get; set; }
        public double? Rsi19 { get; set; }
        public double? Rsi20 { get; set; }
        public double? Rsi21 { get; set; }
        public double? Rsi22 { get; set; }
        public double? Rsi23 { get; set; }
        public double? Rsi24 { get; set; }
        public double? Rsi25 { get; set; }
        public double? Rsi26 { get; set; }
        public double? Rsi27 { get; set; }
        public double? Rsi28 { get; set; }
        public double? Rsi29 { get; set; }
        public double? Rsi30 { get; set; }
        public double? Rsi31 { get; set; }
        public double? Rsi32 { get; set; }
        public double? Rsi33 { get; set; }
        public double? Rsi34 { get; set; }
        public double? Rsi35 { get; set; }
        public double? Rsi36 { get; set; }
        public double? Rsi37 { get; set; }
        public double? Rsi38 { get; set; }
        public double? Rsi39 { get; set; }
        public double? Rsi40 { get; set; }
        public double? Rsi41 { get; set; }
        public double? Rsi42 { get; set; }
        public double? Rsi43 { get; set; }
        public double? Rsi44 { get; set; }
        public double? Rsi45 { get; set; }
        public double? Rsi46 { get; set; }
        public double? Rsi47 { get; set; }
        public double? Rsi48 { get; set; }
        public double? Rsi49 { get; set; }
        public double? Rsi50 { get; set; }
        public double? Rsi51 { get; set; }
        public double? Rsi52 { get; set; }
        public double? Rsi53 { get; set; }
        public double? Rsi54 { get; set; }
        public double? Rsi55 { get; set; }
        public double? Rsi56 { get; set; }
        public double? Rsi57 { get; set; }
        public double? Rsi58 { get; set; }
        public double? Rsi59 { get; set; }
        public double? Rsi60 { get; set; }
        public double? Rsi61 { get; set; }
        public double? Rsi62 { get; set; }
        public double? Rsi63 { get; set; }
        public double? Rsi64 { get; set; }
        public double? Rsi65 { get; set; }
        public double? Rsi66 { get; set; }
        public double? Rsi67 { get; set; }
        public double? Rsi68 { get; set; }
        public double? Rsi69 { get; set; }
        public double? Rsi70 { get; set; }
        public double? Rsi71 { get; set; }
        public double? Rsi72 { get; set; }
        public double? Rsi73 { get; set; }
        public double? Rsi74 { get; set; }
        public double? Rsi75 { get; set; }
        public double? Rsi76 { get; set; }
        public double? Rsi77 { get; set; }
        public double? Rsi78 { get; set; }
        public double? Rsi79 { get; set; }
        public double? Rsi80 { get; set; }
        public double? Rsi81 { get; set; }
        public double? Rsi82 { get; set; }
        public double? Rsi83 { get; set; }
        public double? Rsi84 { get; set; }
        public double? Rsi85 { get; set; }
        public double? Rsi86 { get; set; }
        public double? Rsi87 { get; set; }
        public double? Rsi88 { get; set; }
        public double? Rsi89 { get; set; }
        public double? Rsi90 { get; set; }
        public double? Rsi91 { get; set; }
        public double? Rsi92 { get; set; }
        public double? Rsi93 { get; set; }
        public double? Rsi94 { get; set; }
        public double? Rsi95 { get; set; }
        public double? Rsi96 { get; set; }
        public double? Rsi97 { get; set; }
        public double? Rsi98 { get; set; }
        public double? Rsi99 { get; set; }
        public double? Rsi100 { get; set; }
        public double? Rsi101 { get; set; }
        public double? Rsi102 { get; set; }
        public double? Rsi103 { get; set; }
        public double? Rsi104 { get; set; }
        public double? Rsi105 { get; set; }
        public double? Rsi106 { get; set; }
        public double? Rsi107 { get; set; }
        public double? Rsi108 { get; set; }
        public double? Rsi109 { get; set; }
        public double? Rsi110 { get; set; }
        public double? Rsi111 { get; set; }
        public double? Rsi112 { get; set; }
        public double? Rsi113 { get; set; }
        public double? Rsi114 { get; set; }
        public double? Rsi115 { get; set; }
        public double? Rsi116 { get; set; }
        public double? Rsi117 { get; set; }
        public double? Rsi118 { get; set; }
        public double? Rsi119 { get; set; }
        public double? Rsi120 { get; set; }
        public double? Rsi121 { get; set; }
        public double? Rsi122 { get; set; }
        public double? Rsi123 { get; set; }
        public double? Rsi124 { get; set; }
        public double? Rsi125 { get; set; }
        public double? Rsi126 { get; set; }
        public double? Rsi127 { get; set; }
        public double? Rsi128 { get; set; }
        public double? Rsi129 { get; set; }
        public double? Rsi130 { get; set; }
        public double? Rsi131 { get; set; }
        public double? Rsi132 { get; set; }
        public double? Rsi133 { get; set; }
        public double? Rsi134 { get; set; }
        public double? Rsi135 { get; set; }
        public double? Rsi136 { get; set; }
        public double? Rsi137 { get; set; }
        public double? Rsi138 { get; set; }
        public double? Rsi139 { get; set; }
        public double? Rsi140 { get; set; }
        public double? Rsi141 { get; set; }
        public double? Rsi142 { get; set; }
        public double? Rsi143 { get; set; }
        public double? Rsi144 { get; set; }
        public double? Rsi145 { get; set; }
        public double? Rsi146 { get; set; }
        public double? Rsi147 { get; set; }
        public double? Rsi148 { get; set; }
        public double? Rsi149 { get; set; }
        public double? Rsi150 { get; set; }
        public double? Rsi151 { get; set; }
        public double? Rsi152 { get; set; }
        public double? Rsi153 { get; set; }
        public double? Rsi154 { get; set; }
        public double? Rsi155 { get; set; }
        public double? Rsi156 { get; set; }
        public double? Rsi157 { get; set; }
        public double? Rsi158 { get; set; }
        public double? Rsi159 { get; set; }
        public double? Rsi160 { get; set; }
        public double? Rsi161 { get; set; }
        public double? Rsi162 { get; set; }
        public double? Rsi163 { get; set; }
        public double? Rsi164 { get; set; }
        public double? Rsi165 { get; set; }
        public double? Rsi166 { get; set; }
        public double? Rsi167 { get; set; }
        public double? Rsi168 { get; set; }
        public double? Rsi169 { get; set; }
        public double? Rsi170 { get; set; }
        public double? Rsi171 { get; set; }
        public double? Rsi172 { get; set; }
        public double? Rsi173 { get; set; }
        public double? Rsi174 { get; set; }
        public double? Rsi175 { get; set; }
        public double? Rsi176 { get; set; }
        public double? Rsi177 { get; set; }
        public double? Rsi178 { get; set; }
        public double? Rsi179 { get; set; }
        public double? Rsi180 { get; set; }
        public double? Rsi181 { get; set; }
        public double? Rsi182 { get; set; }
        public double? Rsi183 { get; set; }
        public double? Rsi184 { get; set; }
        public double? Rsi185 { get; set; }
        public double? Rsi186 { get; set; }
        public double? Rsi187 { get; set; }
        public double? Rsi188 { get; set; }
        public double? Rsi189 { get; set; }
        public double? Rsi190 { get; set; }
        public double? Rsi191 { get; set; }
        public double? Rsi192 { get; set; }
        public double? Rsi193 { get; set; }
        public double? Rsi194 { get; set; }
        public double? Rsi195 { get; set; }
        public double? Rsi196 { get; set; }
        public double? Rsi197 { get; set; }
        public double? Rsi198 { get; set; }
        public double? Rsi199 { get; set; }
        public double? Rsi200 { get; set; }
        public double? Rsi201 { get; set; }
        public double? Rsi202 { get; set; }
        public double? Rsi203 { get; set; }
        public double? Rsi204 { get; set; }
        public double? Rsi205 { get; set; }
        public double? Rsi206 { get; set; }
        public double? Rsi207 { get; set; }
        public double? Rsi208 { get; set; }
        public double? Rsi209 { get; set; }
        public double? Rsi210 { get; set; }
        public double? Rsi211 { get; set; }
        public double? Rsi212 { get; set; }
        public double? Rsi213 { get; set; }
        public double? Rsi214 { get; set; }
        public double? Rsi215 { get; set; }
        public double? Rsi216 { get; set; }
        public double? Rsi217 { get; set; }
        public double? Rsi218 { get; set; }
        public double? Rsi219 { get; set; }
        public double? Rsi220 { get; set; }
        public double? Rsi221 { get; set; }
        public double? Rsi222 { get; set; }
        public double? Rsi223 { get; set; }
        public double? Rsi224 { get; set; }
        public double? Rsi225 { get; set; }
        public double? Rsi226 { get; set; }
        public double? Rsi227 { get; set; }
        public double? Rsi228 { get; set; }
        public double? Rsi229 { get; set; }
        public double? Rsi230 { get; set; }
        public double? Rsi231 { get; set; }
        public double? Rsi232 { get; set; }
        public double? Rsi233 { get; set; }
        public double? Rsi234 { get; set; }
        public double? Rsi235 { get; set; }
        public double? Rsi236 { get; set; }
        public double? Rsi237 { get; set; }
        public double? Rsi238 { get; set; }
        public double? Rsi239 { get; set; }
        public double? Rsi240 { get; set; }
        public double? Rsi241 { get; set; }
        public double? Rsi242 { get; set; }
        public double? Rsi243 { get; set; }
        public double? Rsi244 { get; set; }
        public double? Rsi245 { get; set; }
        public double? Rsi246 { get; set; }
        public double? Rsi247 { get; set; }
        public double? Rsi248 { get; set; }
        public double? Rsi249 { get; set; }
        public double? Rsi250 { get; set; }
        public double? Rsi251 { get; set; }
        public double? Rsi252 { get; set; }
        public double? Rsi253 { get; set; }
        public double? Rsi254 { get; set; }
        public double? Rsi255 { get; set; }
        public double? Rsi256 { get; set; }

        public RsiModel()
        {
        }
    }
}
